# CONCLUSIONS: INVASIVE MITES ARE AN INCREASINGLY LARGE PROBLEM FOR FLORIDA

## Main Findings

The principal findings of our experiments are: 

1. *Phyllocoptes fructiphilus* is present in multiple cities in northern Florida
1. The predatory mite *Amblyseius swirskii* is attracted to roses infected *Rose rosette emaravirus* (RRV), displaying symptoms of Rose Rosette Disease (RRD)
1. Infected roses have higher levels of defense-related terpenes, including \textgamma-Muurolene, \textbeta-Caryophyllene, and D-Limonene, some of which may be attractive to *A. swirskii*
1. ASM-treated plants had higher similarity in their Volatile Organic Compound (VOC) profiles to one another than to the VOCs released from healthy or RRV-infected plants
1. Systemic Acquired Resistance (SAR) via acibenzolar-S-methyl (ASM) does not appear to significantly reduce populations of *P. fructiphilus*
1. Preliminary evidence that *P. fructiphilus* populations may be reduced by spirotetramat applications, or possibly heavy pruning when RRD is not present
1. Orchid Fleck Virus (OFV) is present in common ornamental groundcover plants in Florida. 
1. *Brevipalpus californicus* *sensu lato*, a known vector of OFV, were found on OFV-infected plants


## Invasive Species Continue to be a Problem

The aim of our research was to address the emerging problems caused by the recent invasions of mites and the plant viruses they vector to northern Florida. Florida is a hotspot for invasive species in the mainland US, due to a combination of its unique geography, climate, rapid development and a multitude of invasion pathways [@Simberloff1997; @Williams2007; @Card2018]. Invasive species are often harmful to ecosystem services and modify ecosystems to the detriment of native species [@Gordon1998]. Efforts to manage invasive species costs the state of Florida ~\$45M each year [@Hiatt2019]. Many Florida programs have been developed to raise public awareness about the threats of invasive species, as well as encouraging the reporting of invasive species by the public [@Wallace2016]. In the last three years our lab has discovered recent introductions of two invasive of mite-virus-pathosystems previously unreported in Florida. The new invasive mite (*P. fructiphilus*) and the new mite-vectored virus (OFV) were both encountered on ornamental plants commonly found in the landscape of the southeastern US, representing yet another chapter in the story of Florida invasion ecology. These organisms have a high possibility of becoming established invasive species in Florida if preventative actions are not taken. Invasive species such as these mites are thought to mainly disperse through short distances via local spread around established focal populations (diffusive dispersal), while long-distance jumps are more often due to human movements [@Garnas2016; @Suarez2001; @Novak2001; @Higgins1999; @Ibrahim1996]. A further examination of population dynamics, genetic variation and/or spatial structure of mite populations should provide evidence for which pathways of introduction are most prevalent for *P. fructiphilus*, RRD and OFV [@Boubou2012; @Boubou2010; @Navia2005; @Williams2007]. The movement of these mite vectors is important, because arthropod movement is thought to be generally underestimated for past outbreaks and introductions [@Garnas2016]. It is possible that the introduction of *P. fructiphilus* was a natural occurrence: Although *P. fructiphilus* are not very good at dispersal by walking [@Galvao2012; @Melo2014; @Calvet2020], they are known to disperse aerially over a hundred meters away from infested areas by ballooning on air currents [@Bergh1997; @Maggio2012; @Majer2021]. The short distances between mite-infested roses in Georgia, Alabama and Florida suggest the possibility of multiple routes of *P. fructiphilus* introduction, but eriophyid mites have also been found to move on contaminated clothing and equipment [@Duffner2001]. In addition, the movements of plant pathogens such as RRV or OFV is thought to be partially driven by socioeconomic factors and the movement of plants by people [@Nelson2015; @Katsiani2020], via the movement of infected materials and seed through trade networks [@Chapman2017; @Liebhold2012; @Pautasso2014; @Schoebel2014; @MoslonkaLefebvre2011; @Hulme2008; @Westphal2007; @Jeger2007]. There is good evidence for the movement of mites and their viruses by humans in both pathosystems. Specifically, the first detection of RRD in Florida was due to interceptions of infected plant material imported from another wholesaler of roses [@Babu2014]. The primary driver in the original spread of RRD eastwards is thought to be due to the movement of the invasive *Rosa multiflora*, a rose which was intentionally planted as living fences and moved frequently by humans [@Patterson1976]. *R. multiflora* became such a concerning nuisance weed in some states that *P. fructiphilus* were once considered for their potential to control the weed with RRD itself [@Epstein1999; @Epstein1997; @Hindal1988; @Hindal1988a]. Humans play an even larger role in the distribution and movement of OFV: Orchid fleck has a nearly global distribution that is thought to be associated with the international trade of orchids [@Kubo2009; @Blanchfield2001]. Furthermore, tenuipalpid mites are not known to disperse very far by walking, and few (< 1\%) mites were seen to disperse even when wind speeds reached 30 and 40 km/h$_{-1}$ in lab experiments [@Alves2005], which suggests that their potential for natural dispersal is low. The spread of these mite-plant-virus pathosystems is likely due to the movement of plants from larger horticultural entities rather than individuals: Studies and simulations of seed networks have revealed that seed companies and similarly large horticultural operations have greater potential to spread plant pathogens than informal seed systems run by smaller groups [@Coomes2015; @Biemond2013]. This is partially due to the greater ability of large growers to spread infected plant materials at a greater scale than smaller trade systemsor individuals [@Biemond2013]. These findings emphasize the important responsibility of larger plant producers to carefully monitor for and eradicate pests and suspected plant pathogens: @Nelson2015 simulated the effects of quarantines on preventing the spread of a pathogen through an idealized plant trade network and found that increasing the number of growers and wholesalers generally an increased number of infections. Even so, more inspections decreased the chances of initiating an epidemic [@Nelson2015]. They concluded that plant pathogen epidemics were most likely to be prevented via quarantine of growers and wholesalers of plants [@Nelson2015]. This emphasizes how important it is that larger horticultural companies maintain clean operations free of pests and pathogens in order to prevent the further spread of these diseases into Florida.

In conclusion, is increasingly important to monitor for these mite-plant-virus pathosystems in the southeast. Future research should focus on determining the most efficient ways to prevent their further spread into Florida.