# BIOGRAPHICAL SKETCH {-}

Austin N Fife received his B.S. degree in biology - zoology emphasis at Brigham Young University - Idaho at Rexburg. During his undergraduate degree, he conducted research on the distribution of the endemic St. Anthony Dunes Tiger Beetle *Cicendela arenicola*. He went on to receive a M.S. in entomology at the University of Idaho while working at the Kimberly Research and Extension Center on potato psyllids *Bactericera cockerelli* and host plant resistance. He received his PhD in entomology and nematology at the University of Florida in 2021 while working at the North Florida Research and Education Center in Quincy, FL. There he published the first reports on the introduction of two invasive mite-plant-virus pathosystems in northern Florida: he was the first to detect the eriophyid mite *Phyllocoptes fructiphilus* in northern Florida, and also first to record *Orchid fleck dichorhavirus* (OFV) infecting three new ornamental plant hosts. His primary research focused on the potential of plant defenses to control *P. fructiphilus* and RRV. His research covered a variety of topics, including acarology, chemical ecology, induced plant defenses, biological control, and plant-pathogen-arthropod interactions. As a former Eagle Scout from Idaho, he loves to spend time outdoors with his wife, Liz and his two (soon to be three) lovely daughters, Violet, Juniper and {insert plant name here}.

