<!--
The bib chunk below must go last in this document according to how R Markdown renders.  More info is at http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html
-->

<!-- 
If you'd like to change the name of the bibliography to something else,
delete "References" and replace it.
-->

# REFERENCES {-}
<!-- This manually sets the header for this unnumbered chapter. -->
\singlespacing

\markboth{References}{References}

<!-- To remove the indentation of the first entry. -->
\noindent

<!-- To create a hanging indent and spacing between entries.  These three lines
may need to be removed for styles that don't require the hanging indent. -->


\setlength{\parindent}{-0.20in}
\setlength{\leftskip}{0.20in}
\setlength{\parskip}{8pt}




<!--This manually sets the location of the references to here-->
<div id="refs"></div>

\newpage

# BIOGRAPHICAL SKETCH {-}

Austin N. Fife received his B.S. degree in biology - zoology emphasis at Brigham Young University - Idaho at Rexburg, a M.S. in entomology at the University of Idaho at Moscow, and a Ph.D. in entomology and nematology at the University of Florida, Gainesville, where he specialized in acarology, biological control, chemical ecology, vector biology and plant-pathogen-arthropod interactions. He loves to spend time outdoors with his wife Liz and his two lovely daughters Violet and Juniper.


<!-- This is just for testing with more citations for the bibliography at the
end.  Add other entries into the list here if you'd like them to appear in the
bibliography even if they weren't explicitly cited in the document. -->

---
nocite: | 
  @Broussard2007, @Baker1987, @Beard2015, @Fantz2008b, @Fantz2009, @Fantz2015, @Masiero2020, @Wang2014, @Xie2021, @Xie2016, @Ismay2021, @Wickham2019, @Pebesma2018, @Wickham2016, @Cheng2021, @Appelhans2019, @Zhu2021, @Wickham2021, @Arnold2021, @Qiu2021, @WinstonChang2014, @Urbanek2020, @Ooms2021, @Wickham2019a, @Appelhans2021, @Vaidyanathan2020, @Garnier2021, @Ram2018, @Wickham2021a, @Urbanek2021, @Dunnington2021, @Wickham2021b, @Grolemund2011, @Feinerer2008, @Chang2019, @Neuwirth2014, @Bates2015, @Fox2019, @Hothorn2008, @Lenth2021, @Wickham2019b, @Bischl2016, @vanBuuren2011, @Tennekes2018, @Tierney2021, @Kassambara2020, @Mueller2021, @Konopka2020, @Eddelbuettel2018, @Schloerke2021, @Henry2021, @Ottolinger2019, @Zeileis2008, @Jackman2020
...
