# ACKNOWLEDGMENTS

I would like to give special thanks for the Tallahassee Museum and their patience, cooperation, and support with collecting plant samples. I am thankful for the USDA-APHIS PPQ Beltsville laboratory for their support in the identification and confirmation OFV isolates, as well as *Brevipalpus* mite identification at the USDA-ARS. I also want to recognize Drs. Sam Bolton, FDACS and Aline Tassi, Univ. of Sao Paulo, Brazil for checking the mites we have sent for species validation. I appreciate Dr. Marc S. Frank's helpful identification of the Liriopogons collected. I am especially beholden to the late Dr. Gary Bauchan for his brilliant Cryo-SEM images, and his contributions to the field of acarology. He will be greatly missed. This research was partly funded by the USDA National Institute of Food and Agriculture, Hatch project FLA-NFC-005607 and USDA-AFRI-CPPM 2017-70006-27268. Funds were also contributed by The Florida Nursery, Growers and Landscape Association's (FNGLA) Endowed Research Funds. Mention of trade names or commercial products in this publication is solely for the purpose of providing specific information and does not imply recommendation or endorsement by the USDA; USDA is an equal opportunity provider and employer. I am thankful for the time, patience, and dedication of my committee members Drs. Gary Knox and Daniel Carrillo. I am also incredibly grateful to my Co-PIs, Dr. Mathews Paret and Dr. Xavier Martini, who have helped to lead, guide, inspire, and redirect me on the path to becoming a young researcher. 

I am obliged to my goodly parents for teaching me about the importance of learning, and for the heritage and language of my maternal grandmother, which has blessed my life so much. *Los abuelos nunca mueren, sólo se vuelven invisibles.* Most of all, I am eternally indebted to my spouse, Liz, as well as my daughters Violet and Juniper for their endurance and support during these most harrowing years of my life. Thank you.
